---

- name: Configuring cron
  template: >
    src=etc-cron-d-ansible.j2
    dest=/etc/cron.d/{{ cron_task_group_name }}
    owner=root
    group=root
    mode=0644
  tags:
    - system
    - cron
    - config
